### PR TITLE
remove old pull request template

### PR DESCRIPTION
**Pull request by toastal**
**Description of the change**

This caused an issue with case-insensitive filesystems

---

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by hdgarrood** [comment]
Can we fold this content into the new one please?

**Comment by toastal** [comment]
You tell me? I suppose so.

**Comment by toastal** [comment]
@hdgarrood But I did add that section back for Prequisites

**Comment by garyb** [comment]
Thanks! That old template was added explicitly because I had to make the point repeatedly about adhering to the spec rather than MDN... I guess I need to check all the other `-web` repos now as they probably all have similar conflicting templates.

**Comment by thomashoneyman** [comment]
Ugh, sorry about this. I can make that update for you, @garyb.

**Comment by garyb** [comment]
No problem! I didn't think to mention it when I saw the PRs going up. If you have a script or something that makes it easy, go ahead, otherwise I don't mind doing it 🙂.

**Comment by thomashoneyman** [comment]
I don’t, but I have a lunch break 😅 if they haven’t been done by then (about 4 hours from now) I can jump on it. Thanks!

**Comment by garyb** [comment]
Uh, actually, I'm having trouble with it exactly because of case-insensitive filesystem reasons, so if you do have time to do it, that would be great! 😄

**Pull request merged**
